
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2026-06-02T20:22:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dfdefa40eaf2c904acf0ff6f7d32442597280c9",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
